#include "petsc_webserver.h"


PetscErrorCode create_tcpaccept_entry_bag(tcpaccept_entry **entryptr, PetscBag *bagptr)
{
  PetscErrorCode ierr;
  tcpaccept_entry *entry;
  PetscBag        bag;
  PetscFunctionBeginUser;
  ierr = PetscBagCreate(PETSC_COMM_WORLD,sizeof(tcpaccept_entry),&bag);CHKERRQ(ierr);
  ierr = PetscBagGetData(bag,(void**)&entry);CHKERRQ(ierr);
  ierr = PetscBagSetName(bag,"tcpaccept_entry","An entry generated by the tcpaccept program");CHKERRQ(ierr);
  ierr = PetscBagRegisterInt(bag,&entry->pid,-1,"pid","Process ID that accepted the connection");CHKERRQ(ierr);
  ierr = PetscBagRegisterInt(bag,&entry->ip,4,"ip","IP address version");CHKERRQ(ierr);
  ierr = PetscBagRegisterInt(bag,&entry->rport,"rport","Remote port");CHKERRQ(ierr);
  ierr = PetscBagRegisterInt(bag,&entry->lport,"lport","Local port");CHKERRQ(ierr);
  ierr = PetscBagRegisterString(bag,&entry->laddr,IP_ADDR_MAX_LEN,"0.0.0.0","laddr","Local IP address");CHKERRQ(ierr);
  ierr = PetscBagRegisterString(bag,&entry->raddr,IP_ADDR_MAX_LEN,"0.0.0.0","raddr","Remote IP address");CHKERRQ(ierr);
  ierr = PetscBagRegisterString(bag,&entry->comm,COMM_MAX_LEN,"[unknown]","comm","Process name");CHKERRQ(ierr);
  
  *entryptr = entry;
  *bagptr = bag;
  PetscFunctionReturn(0);
}
